# Generated by Django 4.0.4 on 2022-05-08 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AkaName',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('person_id', models.IntegerField()),
                ('name', models.CharField(blank=True, max_length=1000, null=True)),
                ('imdb_index', models.CharField(blank=True, max_length=3, null=True)),
                ('name_pcode_cf', models.CharField(blank=True, max_length=11, null=True)),
                ('name_pcode_nf', models.CharField(blank=True, max_length=11, null=True)),
                ('surname_pcode', models.CharField(blank=True, max_length=11, null=True)),
                ('md5sum', models.CharField(blank=True, max_length=65, null=True)),
            ],
            options={
                'db_table': 'aka_name',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AkaTitle',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('movie_id', models.IntegerField()),
                ('title', models.CharField(blank=True, max_length=1000, null=True)),
                ('imdb_index', models.CharField(blank=True, max_length=4, null=True)),
                ('kind_id', models.IntegerField()),
                ('production_year', models.IntegerField(blank=True, null=True)),
                ('phonetic_code', models.CharField(blank=True, max_length=5, null=True)),
                ('episode_of_id', models.IntegerField(blank=True, null=True)),
                ('season_nr', models.IntegerField(blank=True, null=True)),
                ('episode_nr', models.IntegerField(blank=True, null=True)),
                ('note', models.CharField(blank=True, max_length=72, null=True)),
                ('md5sum', models.CharField(blank=True, max_length=32, null=True)),
            ],
            options={
                'db_table': 'aka_title',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.BooleanField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.BooleanField()),
                ('is_active', models.BooleanField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CastInfo',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('person_id', models.IntegerField()),
                ('movie_id', models.IntegerField()),
                ('person_role_id', models.IntegerField(blank=True, null=True)),
                ('note', models.CharField(blank=True, max_length=1000, null=True)),
                ('nr_order', models.IntegerField(blank=True, null=True)),
                ('role_id', models.IntegerField()),
            ],
            options={
                'db_table': 'cast_info',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CharName',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=1000)),
                ('imdb_index', models.CharField(blank=True, max_length=2, null=True)),
                ('imdb_id', models.IntegerField(blank=True, null=True)),
                ('name_pcode_nf', models.CharField(blank=True, max_length=5, null=True)),
                ('surname_pcode', models.CharField(blank=True, max_length=5, null=True)),
                ('md5sum', models.CharField(blank=True, max_length=32, null=True)),
            ],
            options={
                'db_table': 'char_name',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CompanyName',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=1000)),
                ('country_code', models.CharField(blank=True, max_length=6, null=True)),
                ('imdb_id', models.IntegerField(blank=True, null=True)),
                ('name_pcode_nf', models.CharField(blank=True, max_length=5, null=True)),
                ('name_pcode_sf', models.CharField(blank=True, max_length=5, null=True)),
                ('md5sum', models.CharField(blank=True, max_length=32, null=True)),
            ],
            options={
                'db_table': 'company_name',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CompanyType',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('kind', models.CharField(blank=True, max_length=32, null=True)),
            ],
            options={
                'db_table': 'company_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CompCastType',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('kind', models.CharField(max_length=32)),
            ],
            options={
                'db_table': 'comp_cast_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CompleteCast',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('movie_id', models.IntegerField(blank=True, null=True)),
                ('subject_id', models.IntegerField()),
                ('status_id', models.IntegerField()),
            ],
            options={
                'db_table': 'complete_cast',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.SmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='InfoType',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('info', models.CharField(max_length=32)),
            ],
            options={
                'db_table': 'info_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('keyword', models.CharField(max_length=1000)),
                ('phonetic_code', models.CharField(blank=True, max_length=5, null=True)),
            ],
            options={
                'db_table': 'keyword',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='KindType',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('kind', models.CharField(blank=True, max_length=15, null=True)),
            ],
            options={
                'db_table': 'kind_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LinkType',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('link', models.CharField(max_length=32)),
            ],
            options={
                'db_table': 'link_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MovieCompanies',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('movie_id', models.IntegerField()),
                ('company_id', models.IntegerField()),
                ('company_type_id', models.IntegerField()),
                ('note', models.CharField(blank=True, max_length=1000, null=True)),
            ],
            options={
                'db_table': 'movie_companies',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MovieInfo',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('movie_id', models.IntegerField()),
                ('info_type_id', models.IntegerField()),
                ('info', models.CharField(max_length=1000)),
                ('note', models.CharField(blank=True, max_length=1000, null=True)),
            ],
            options={
                'db_table': 'movie_info',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MovieInfoIdx',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('movie_id', models.IntegerField()),
                ('info_type_id', models.IntegerField()),
                ('info', models.CharField(max_length=1000)),
                ('note', models.CharField(blank=True, max_length=1, null=True)),
            ],
            options={
                'db_table': 'movie_info_idx',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MovieKeyword',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('movie_id', models.IntegerField()),
                ('keyword_id', models.IntegerField()),
            ],
            options={
                'db_table': 'movie_keyword',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MovieLink',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('movie_id', models.IntegerField()),
                ('linked_movie_id', models.IntegerField()),
                ('link_type_id', models.IntegerField()),
            ],
            options={
                'db_table': 'movie_link',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Name',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=1000)),
                ('imdb_index', models.CharField(blank=True, max_length=9, null=True)),
                ('imdb_id', models.IntegerField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, max_length=1, null=True)),
                ('name_pcode_cf', models.CharField(blank=True, max_length=5, null=True)),
                ('name_pcode_nf', models.CharField(blank=True, max_length=5, null=True)),
                ('surname_pcode', models.CharField(blank=True, max_length=5, null=True)),
                ('md5sum', models.CharField(blank=True, max_length=32, null=True)),
            ],
            options={
                'db_table': 'name',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PersonInfo',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('person_id', models.IntegerField()),
                ('info_type_id', models.IntegerField()),
                ('info', models.CharField(max_length=1000)),
                ('note', models.CharField(blank=True, max_length=1000, null=True)),
            ],
            options={
                'db_table': 'person_info',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RoleType',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('role', models.CharField(max_length=32)),
            ],
            options={
                'db_table': 'role_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Title',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=1000)),
                ('imdb_index', models.CharField(blank=True, max_length=5, null=True)),
                ('kind_id', models.IntegerField()),
                ('production_year', models.IntegerField(blank=True, null=True)),
                ('imdb_id', models.IntegerField(blank=True, null=True)),
                ('phonetic_code', models.CharField(blank=True, max_length=5, null=True)),
                ('episode_of_id', models.IntegerField(blank=True, null=True)),
                ('season_nr', models.IntegerField(blank=True, null=True)),
                ('episode_nr', models.IntegerField(blank=True, null=True)),
                ('series_years', models.CharField(blank=True, max_length=49, null=True)),
                ('md5sum', models.CharField(blank=True, max_length=32, null=True)),
            ],
            options={
                'db_table': 'title',
                'managed': False,
            },
        ),
    ]
