# Generated by Django 4.0.4 on 2022-05-08 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estimation', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='akaname',
            options={},
        ),
        migrations.AlterModelOptions(
            name='akatitle',
            options={},
        ),
        migrations.AlterModelOptions(
            name='castinfo',
            options={},
        ),
        migrations.AlterModelOptions(
            name='charname',
            options={},
        ),
        migrations.AlterModelOptions(
            name='companyname',
            options={},
        ),
        migrations.AlterModelOptions(
            name='companytype',
            options={},
        ),
        migrations.AlterModelOptions(
            name='compcasttype',
            options={},
        ),
        migrations.AlterModelOptions(
            name='completecast',
            options={},
        ),
        migrations.AlterModelOptions(
            name='infotype',
            options={},
        ),
        migrations.AlterModelOptions(
            name='keyword',
            options={},
        ),
        migrations.AlterModelOptions(
            name='kindtype',
            options={},
        ),
        migrations.AlterModelOptions(
            name='linktype',
            options={},
        ),
        migrations.AlterModelOptions(
            name='moviecompanies',
            options={},
        ),
        migrations.AlterModelOptions(
            name='movieinfo',
            options={},
        ),
        migrations.AlterModelOptions(
            name='movieinfoidx',
            options={},
        ),
        migrations.AlterModelOptions(
            name='moviekeyword',
            options={},
        ),
        migrations.AlterModelOptions(
            name='movielink',
            options={},
        ),
        migrations.AlterModelOptions(
            name='name',
            options={},
        ),
        migrations.AlterModelOptions(
            name='personinfo',
            options={},
        ),
        migrations.AlterModelOptions(
            name='roletype',
            options={},
        ),
        migrations.AlterModelOptions(
            name='title',
            options={},
        ),
    ]
