# Generated by Django 4.0.4 on 2022-05-08 21:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('estimation', '0002_delete_authgroup_delete_authgrouppermissions_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AuthGroup',
        ),
        migrations.DeleteModel(
            name='AuthGroupPermissions',
        ),
        migrations.DeleteModel(
            name='AuthPermission',
        ),
        migrations.DeleteModel(
            name='AuthUser',
        ),
        migrations.DeleteModel(
            name='AuthUserGroups',
        ),
        migrations.DeleteModel(
            name='AuthUserUserPermissions',
        ),
        migrations.DeleteModel(
            name='DjangoAdminLog',
        ),
        migrations.DeleteModel(
            name='DjangoContentType',
        ),
        migrations.DeleteModel(
            name='DjangoMigrations',
        ),
        migrations.DeleteModel(
            name='DjangoSession',
        ),
        migrations.RemoveField(
            model_name='akaname',
            name='person_id',
        ),
        migrations.AddField(
            model_name='akaname',
            name='person',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='estimation.name'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='akaname',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='akatitle',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='akatitle',
            name='kind_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estimation.kindtype'),
        ),
        migrations.AlterField(
            model_name='akatitle',
            name='movie_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estimation.title'),
        ),
        migrations.AlterField(
            model_name='castinfo',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='castinfo',
            name='movie_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estimation.title'),
        ),
        migrations.AlterField(
            model_name='castinfo',
            name='person_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estimation.name'),
        ),
        migrations.AlterField(
            model_name='castinfo',
            name='person_role_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='estimation.charname'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='castinfo',
            name='role_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estimation.roletype'),
        ),
        migrations.AlterField(
            model_name='charname',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='companyname',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='companytype',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='compcasttype',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='completecast',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='completecast',
            name='movie_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='estimation.title'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='infotype',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='keyword',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='kindtype',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='linktype',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='moviecompanies',
            name='company_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estimation.companyname'),
        ),
        migrations.AlterField(
            model_name='moviecompanies',
            name='company_type_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estimation.companytype'),
        ),
        migrations.AlterField(
            model_name='moviecompanies',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='moviecompanies',
            name='movie_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estimation.title'),
        ),
        migrations.AlterField(
            model_name='movieinfo',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='movieinfo',
            name='info_type_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estimation.infotype'),
        ),
        migrations.AlterField(
            model_name='movieinfo',
            name='movie_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estimation.title'),
        ),
        migrations.AlterField(
            model_name='movieinfoidx',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='movieinfoidx',
            name='info_type_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estimation.infotype'),
        ),
        migrations.AlterField(
            model_name='movieinfoidx',
            name='movie_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estimation.title'),
        ),
        migrations.AlterField(
            model_name='moviekeyword',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='moviekeyword',
            name='keyword_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estimation.keyword'),
        ),
        migrations.AlterField(
            model_name='moviekeyword',
            name='movie_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estimation.title'),
        ),
        migrations.AlterField(
            model_name='movielink',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='movielink',
            name='link_type_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estimation.linktype'),
        ),
        migrations.AlterField(
            model_name='movielink',
            name='linked_movie_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='linked_movies', to='estimation.title'),
        ),
        migrations.AlterField(
            model_name='movielink',
            name='movie_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movies', to='estimation.title'),
        ),
        migrations.AlterField(
            model_name='name',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='personinfo',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='personinfo',
            name='info_type_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estimation.infotype'),
        ),
        migrations.AlterField(
            model_name='personinfo',
            name='person_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estimation.name'),
        ),
        migrations.AlterField(
            model_name='roletype',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='title',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='title',
            name='kind_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estimation.kindtype'),
        ),
    ]
